### ISSUE TITLE
add field for user's answer in trial table

### ISSUE THREAD

**Issue by boomsbloom** [StanfordCosyne/math-intervention-api#1]
should be int that they answered with. for verification tasks it can be 0 for equal and 1 for not equal (or text if that is more straightforward)

**Comment by cbattista** [comment]
yep makes sense - can do 0/1 for ver because that way we can still use the
int type

On Tue, Jan 19, 2016 at 4:39 PM, Jonathan Nicholas <notifications@github.com

**Comment by boomsbloom** [comment]
cool -- I've called this 'answer' in the game code.

**Comment by boomsbloom** [comment]
actually I'm going to change it to 'response' for clarity
