### ISSUE TITLE
session API test fail

### ISSUE THREAD

**Issue by cbattista** [StanfordCosyne/math-intervention-api#17]
======================================================================
FAIL: it should have an open session for a logged in user
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_session.py", line 63, in test_login_and_session_get
    self.assertTrue(json_data[0]==1 and type(json_data[1])==list)
AssertionError

**Comment by cbattista** [comment]
basically what's going on here is that it's getting the wrong session # for some reason.  returning 2 instead of 1 for the particular test.

**Comment by boomsbloom** [comment]
Is this because line 59 in session.py?

#TODO - check to see whether we are on the same training day - would want to resume previous session in this case, and not close this one

**Comment by cbattista** [comment]
shouldn't be (that test used to workl).  the user is getting logged in for
the first time in the test (line 57), and then the we get the session in
the request on line 60.

**Comment by cbattista** [comment]
i feel like it's probably related to this -
1adeb4e96e35b0aef708ec4caeaf4b6c065dea5c
- in some way

**Comment by boomsbloom** [comment]
thats what I thought too but I went through and reverted those changes and its still broken

**Comment by boomsbloom** [comment]
actually nvm found it

**Comment by cbattista** [comment]
yeah it was session.openSession(row['username']) in the PUT in the user
page, right?

**Comment by boomsbloom** [comment]
yeah. so according to my wonderfully specific comment "put here for pilot" ( -_- ) that is there because for the pilot we are just creating users and sending them on to the tasks rather than logging them in (which is why I'm using PUT rather than GET).

**Comment by cbattista** [comment]
hehe yeppers - so should do the custom for pilot stuff in the UI.  so you'd
do 3 asynchronous requests...

user PUT - create the user
user GET - log the user in
session GET - get the session #

...and you should be golden

the reasoning behind this is that the UI is customized to the pilot in
terms of the interface, requests, etc...whereas the API should be left as
general purpose as possible - in other words keeping the functionality of
the different API calls as specific as possible so they can be recombined
with ease by other UIs.  for instance, if I wrote a experimenter client UI
to make users, then I wouldn't want to open a session for them when I was
doing that, etc etc - this way as we change research settings, we only have
to modify existing clients or make new clients, w/o having to worry about
API compatibility issues as a result of those changes.

-C

**Comment by boomsbloom** [comment]
cool, yeah that makes sense. I'll factor this out and close the issue with next push

**Comment by cbattista** [comment]
great sounds good
