### ISSUE TITLE
user put request returns 415 unsupported media type

### ISSUE THREAD

**Issue by boomsbloom** [StanfordCosyne/math-intervention-api#3]
have spent some time on this so I figured it was time to ask given the time constraint. on the train with dead comp and doing writing from memory on my phone so apologies for the formatting.

user.py's put function takes a json (it's the get function that doesn't) and creates a new username/password combination, so I'm trying to use it to create a new user with bday/gender in a combined string as username and password. I'm passing the keys 'username', 'password1', and 'password2' (which are checked for compatibility and then password1 is made equal to password) as well as datatype: 'json', contenttype: 'application/json' in the put request. url is pointing to /user/.

that all seems right to me - am I missing something?

**Comment by cbattista** [comment]
Yeah it does - push your stuff and I'll take a look at it...

**Comment by boomsbloom** [comment]
will do once I get to an outlet

**Comment by cbattista** [comment]
it may be that the content should not be sent as json - which is weird
since that's what works with the screener

**Comment by boomsbloom** [comment]
I tried html and text and got the same error and from your code it seems
like it wants json, right?

**Comment by cbattista** [comment]
But it's expecting to get something like
url?username=whatever&password1=something... etc etc

**Comment by boomsbloom** [comment]
just pushed it.
so my memory failed me -- 415 was thrown when I tried 'text' or 'html' with default contenttype and 400 (bad request) is thrown for current code

**Comment by cbattista** [comment]
ok, so a 400 means there's some problem with the data you're sending (also did you commit your changes to common.js login(), it seems like it's still the old version)

**Comment by boomsbloom** [comment]
yeah I did - its in subject.js (it may look old because I haven't touched
the logout() function)

On Mon, Feb 1, 2016 at 8:40 PM, Christian Battista <notifications@github.com

**Comment by boomsbloom** [comment]
re: 400 - that's what I thought, and so I tried a couple things, but what
seems like it should work is non-stringified data, default contenttype, and
'html' datatype as in this top answer:
http://stackoverflow.com/questions/18701282/what-is-content-type-and-datatype-in-an-ajax-request

but that returns a 415

**Comment by cbattista** [comment]
Gotcha - was looking in common

**Comment by cbattista** [comment]
this was your bug - you weren't providing the mandatory fields ('training_program' and 'study')

for your reference if you look in the terminal window you start the api from (e.g., index.py) you can see the error messages it spits out

**Comment by cbattista** [comment]
changes have been pushed to the client

**Comment by boomsbloom** [comment]
oh, yeah I see that error in there now. thanks for helping!

On Mon, Feb 1, 2016 at 9:42 PM, Christian Battista <notifications@github.com

**Comment by cbattista** [comment]
no probs.  let me know what else comes up.
